"""Tests for the CLI entrypoints and argument handling."""

from asyncio import run
from json import dumps
from pathlib import Path

import adparser.conflicts as conflicts_mod
from adparser import cli


def test_cli_smoke_runs_and_writes_outputs(tmp_path: Path, monkeypatch):
    """Full pipeline smoke test: verify outputs are written with expected content."""
    data_dir = tmp_path / "data"
    out_dir = tmp_path / "output"
    data_dir.mkdir()
    out_dir.mkdir()

    blacklist = tmp_path / "blacklist.txt"
    whitelist = tmp_path / "whitelist.txt"
    blacklist.write_text(
        """
# sample
example.com
||ads.example^
(^|\\.)regex.keep$
""".strip(),
        encoding="utf-8",
    )
    whitelist.write_text(
        """
@@||allow.example^
allow-plain.example
""".strip(),
        encoding="utf-8",
    )

    adlists_json = data_dir / "adlists.json"
    whitelists_json = data_dir / "whitelists.json"

    adlists_json.write_text(dumps({"lists": [str(blacklist)]}), encoding="utf-8")
    whitelists_json.write_text(dumps({"lists": [str(whitelist)]}), encoding="utf-8")

    monkeypatch.setattr(cli, "ADLISTS", str(adlists_json), raising=True)
    monkeypatch.setattr(cli, "WHITELISTS", str(whitelists_json), raising=True)
    monkeypatch.setattr(cli, "ADLIST_OUTPUT", str(out_dir / "adlist.txt"), raising=True)
    monkeypatch.setattr(
        cli, "WHITELIST_OUTPUT", str(out_dir / "whitelist.txt"), raising=True
    )

    code = run(cli.main())
    assert code == 0

    ad_out = (out_dir / "adlist.txt").read_text(encoding="utf-8")
    wl_out = (out_dir / "whitelist.txt").read_text(encoding="utf-8")

    assert ad_out.startswith("# Adlist - Generated by Adlist-Parser")
    assert "Total entries:" in ad_out
    assert wl_out.startswith("# Whitelist - Generated by Adlist-Parser")
    assert "Total entries:" in wl_out
    assert "||ads.example^" in ad_out.splitlines()
    assert "||regex.keep^" in ad_out.splitlines()
    assert "example.com" in ad_out.splitlines()
    assert "@@||allow.example^" in wl_out.splitlines()
    assert "allow-plain.example" in wl_out.splitlines()


def test_cli_check_conflicts_argument(tmp_path, monkeypatch, capsys):
    """--check-conflicts runs only conflict detection and exits 0."""
    bl = tmp_path / "blacklist.txt"
    wl = tmp_path / "whitelist.txt"
    bl.write_text("conflict.com\n", encoding="utf-8")
    wl.write_text("conflict.com\n", encoding="utf-8")
    monkeypatch.setattr(conflicts_mod, "BLACKLIST_PATH", bl)
    monkeypatch.setattr(conflicts_mod, "WHITELIST_PATH", wl)
    monkeypatch.setattr(cli, "argv", ["adparser", "--check-conflicts"])

    code = run(cli.main())

    assert code == 0
    out = capsys.readouterr().out
    assert "CONFLICT" in out
    assert any("conflict.com" in ln for ln in out.splitlines())


def test_cli_check_conflicts_no_conflicts(tmp_path, monkeypatch, capsys):
    """--check-conflicts prints clean message when nothing overlaps."""
    bl = tmp_path / "blacklist.txt"
    wl = tmp_path / "whitelist.txt"
    bl.write_text("block.com\n", encoding="utf-8")
    wl.write_text("allow.com\n", encoding="utf-8")
    monkeypatch.setattr(conflicts_mod, "BLACKLIST_PATH", bl)
    monkeypatch.setattr(conflicts_mod, "WHITELIST_PATH", wl)
    monkeypatch.setattr(cli, "argv", ["adparser", "--check-conflicts"])

    code = run(cli.main())

    assert code == 0
    out = capsys.readouterr().out
    assert "No conflicts" in out
