#!/usr/bin/env python3
"""CLI entrypoint for Adlist-Parser.

Runs the pipeline for both the main adlist and the whitelist using
defaults under the repository's ``data/`` and writes results to ``output/``.
"""

from __future__ import annotations

from asyncio import gather, run, sleep, to_thread
from datetime import datetime, timezone
from time import time
from typing import List, Optional, Tuple

from .constants import ADLIST_OUTPUT, ADLISTS, WHITELIST_OUTPUT, WHITELISTS
from .content import generate_list, separate_blocklist_whitelist
from .fetcher import fetch
from .io import load_sources, write_output
from .models import Source
from .redundancy import generate_redundancy_report
from .reporting import generate_report
from .status import GroupedStatusDisplay, StatusSpinner

status_display: Optional[GroupedStatusDisplay] = None


def _generate_header(
    list_type: str,
    total_entries: int,
    domains: int,
    abp_rules: int,
    sources_count: int,
) -> str:
    """Generate header comment block for output files.

    Args:
        list_type: Type of list ('Adlist' or 'Whitelist').
        total_entries: Total number of entries in the list.
        domains: Number of domain entries.
        abp_rules: Number of ABP-style rules.
        sources_count: Number of source lists processed.

    Returns:
        Formatted header comment string.
    """
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S UTC")

    header = f"""# {list_type} - Generated by Adlist-Parser
# https://github.com/Toomas633/Adlist-Parser
#
# Created: {timestamp}
# Total entries: {total_entries:,}
# Domains: {domains:,}
# ABP-style rules: {abp_rules:,}
# Sources processed: {sources_count}
#
# This file is automatically generated. Do not edit manually.
# To update, run: adlist-parser or python -m adparser
#
"""
    return header


async def _fetch_with_progress(sources: List[Source], spinner: StatusSpinner):
    """Fetch sources with progress updates to the spinner."""

    def progress_callback(completed: int, total: int):
        spinner.update_progress(completed, total)

    return await to_thread(fetch, sources, progress_callback)


async def _generate_adlist():
    """Generate merged adlist file from ``ADLISTS`` into ``ADLIST_OUTPUT``."""
    global status_display
    if status_display is None:
        raise RuntimeError("Status display not initialized")
    spinner = status_display.allocate_line()

    sources = await spinner.show_progress(
        "Adlist: Loading sources...", to_thread(load_sources, ADLISTS)
    )

    results: List[Tuple[str, List[str]]]
    failed_sources: List[Source]
    results, failed_sources = await spinner.show_progress(
        "Adlist: Fetching content...", _fetch_with_progress(sources, spinner)
    )

    domains, abp_rules, failed_sources = await spinner.show_progress(
        "Adlist: Processing domains...",
        to_thread(generate_list, results, sources, failed_sources),
    )

    combined = domains + abp_rules
    header = _generate_header(
        "Adlist",
        len(combined),
        len(domains),
        len(abp_rules),
        len(sources),
    )
    await spinner.show_progress(
        "Adlist: Writing output...",
        to_thread(
            write_output, ADLIST_OUTPUT, sorted(set(combined), key=str.lower), header
        ),
    )
    spinner.update_status(
        f"✅ Adlist: Complete - {len(combined)} entries ({len(domains)} domains, {len(abp_rules)} ABP rules)"
    )

    return (
        len(sources),
        len(combined),
        len(domains),
        len(abp_rules),
        failed_sources,
        results,
        sources,
    )


async def _generate_whitelist():
    """Generate merged whitelist file from ``WHITELISTS`` into ``WHITELIST_OUTPUT``."""
    global status_display
    if status_display is None:
        raise RuntimeError("Status display not initialized")
    spinner = status_display.allocate_line()

    sources = await spinner.show_progress(
        "Whitelist: Loading sources...", to_thread(load_sources, WHITELISTS)
    )

    results: List[Tuple[str, List[str]]]
    failed_sources: List[Source]
    results, failed_sources = await spinner.show_progress(
        "Whitelist: Fetching content...", _fetch_with_progress(sources, spinner)
    )

    domains, abp_rules, failed_sources = await spinner.show_progress(
        "Whitelist: Processing domains...",
        to_thread(generate_list, results, sources, failed_sources),
    )

    combined = domains + abp_rules
    header = _generate_header(
        "Whitelist",
        len(combined),
        len(domains),
        len(abp_rules),
        len(sources),
    )
    await spinner.show_progress(
        "Whitelist: Writing output...",
        to_thread(
            write_output, WHITELIST_OUTPUT, sorted(set(combined), key=str.lower), header
        ),
    )
    spinner.update_status(
        f"✅ Whitelist: Complete - {len(combined)} entries ({len(domains)} domains, {len(abp_rules)} ABP rules)"
    )

    return (
        len(sources),
        len(combined),
        len(domains),
        len(abp_rules),
        failed_sources,
        results,
        sources,
    )


async def main() -> int:
    """Main execution function with status updates."""
    global status_display
    start_time = time()

    print("🚀 Starting Adlist-Parser...")
    print("⚡ Processing adlists and whitelists concurrently...")

    status_display = GroupedStatusDisplay(initial_lines_offset=2)

    adlist_result, whitelist_result = await gather(
        _generate_adlist(), _generate_whitelist()
    )

    (
        adlist_sources,
        _adlist_entries,
        _adlist_domains,
        _adlist_abp,
        adlist_failed,
        adlist_fetch_results,
        adlist_all_sources,
    ) = adlist_result
    (
        whitelist_sources,
        _whitelist_entries,
        _whitelist_domains,
        _whitelist_abp,
        whitelist_failed,
        whitelist_fetch_results,
        whitelist_all_sources,
    ) = whitelist_result

    spinner = status_display.allocate_line()

    (
        adlist_entries,
        adlist_domains,
        adlist_abp,
        whitelist_entries,
        whitelist_domains,
        whitelist_abp,
    ) = await spinner.show_progress(
        "Post-processing: Separating blocklist and whitelist entries...",
        _run_post_processing(adlist_sources, whitelist_sources),
    )

    spinner.update_status(
        f"✅ Post-processing complete: Adlist {adlist_entries:,} | Whitelist {whitelist_entries:,}"
    )

    adlist_summary = (
        adlist_sources,
        adlist_entries,
        adlist_domains,
        adlist_abp,
        adlist_failed,
    )
    whitelist_summary = (
        whitelist_sources,
        whitelist_entries,
        whitelist_domains,
        whitelist_abp,
        whitelist_failed,
    )

    generate_redundancy_report(
        adlist_fetch_results, adlist_failed, adlist_all_sources, "Adlists"
    )
    generate_redundancy_report(
        whitelist_fetch_results, whitelist_failed, whitelist_all_sources, "Whitelists"
    )

    generate_report(adlist_summary, whitelist_summary, start_time)

    return 0


if __name__ == "__main__":
    raise SystemExit(run(main()))


async def _run_post_processing(
    adlist_sources: int, whitelist_sources: int
) -> Tuple[int, int, int, int, int, int]:
    adlist_lines = await to_thread(_read_non_comment_lines, ADLIST_OUTPUT)
    whitelist_lines = await to_thread(_read_non_comment_lines, WHITELIST_OUTPUT)

    cleaned_adlist, cleaned_whitelist = await to_thread(
        separate_blocklist_whitelist, adlist_lines, whitelist_lines
    )

    adlist_plain = [e for e in cleaned_adlist if not e.startswith('||')]
    adlist_abp_rules = [e for e in cleaned_adlist if e.startswith('||')]
    whitelist_plain = [e for e in cleaned_whitelist if not e.startswith('@@||')]
    whitelist_abp_rules = [e for e in cleaned_whitelist if e.startswith('@@||')]

    adlist_header = _generate_header(
        "Adlist",
        len(cleaned_adlist),
        len(adlist_plain),
        len(adlist_abp_rules),
        adlist_sources,
    )

    whitelist_header = _generate_header(
        "Whitelist",
        len(cleaned_whitelist),
        len(whitelist_plain),
        len(whitelist_abp_rules),
        whitelist_sources,
    )

    await to_thread(_write_with_header, ADLIST_OUTPUT, adlist_header, cleaned_adlist)
    await to_thread(
        _write_with_header, WHITELIST_OUTPUT, whitelist_header, cleaned_whitelist
    )

    return (
        len(cleaned_adlist),
        len(adlist_plain),
        len(adlist_abp_rules),
        len(cleaned_whitelist),
        len(whitelist_plain),
        len(whitelist_abp_rules),
    )


def _read_non_comment_lines(path: str) -> list[str]:
    """Read file and return non-comment, non-empty stripped lines."""
    with open(path, 'r', encoding='utf-8') as f:
        return [line.strip() for line in f if line.strip() and not line.startswith('#')]


def _write_with_header(path: str, header: str, lines: list[str]) -> None:
    """Write header and lines with LF endings."""
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)
        f.write('\n'.join(lines))
        if lines:
            f.write('\n')
